apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: tracing
spec:
  selector:
    app.kubernetes.io/name: jaeger-tracing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 16686
      name: http
    - protocol: UDP
      port: 14268
      name: thrift
    - protocol: UDP
      port: 14250
      name: proto