apiVersion: v1
data:
  otel-collector-config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: otel-collector.tracing.svc.cluster.local:4317

    exporters:
      jaeger:
        endpoint: jaeger.tracing.svc.cluster.local:14250
        tls:
          insecure: true

    processors:
      batch:

    extensions:
      health_check:

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger]
kind: ConfigMap
metadata:
  name: otel-collector-config
