apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: tracing
spec:
  selector:
    app.kubernetes.io/name: jaeger-tracing
  ports:
    - protocol: UDP
      port: 13133
    - protocol: UDP
      port: 4317