apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-tracing
  namespace: tracing
  labels:
    k8s-app: jaeger-tracing
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger-tracing
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger-tracing
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.40.0
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 16686
            - containerPort: 14268
            - containerPort: 14250
        - name: otel-collector
          image: otel/opentelemetry-collector:0.67.0
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          command:
            - "--config=/etc/otel-collector-config.yaml"
          ports:
            - containerPort: 13133
            - containerPort: 4317
          volumeMounts:
            - mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
              name: ze-config
      volumes:
        - name: ze-config
          configMap:
            name: otel-collector-config