apiVersion: v1
kind: Service
metadata:
  name: tracing-service
spec:
  selector:
    app.kubernetes.io/name: jaeger-tracing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 16686
    - protocol: UDP
      port: 14268
    - protocol: UDP
      port: 14250
    - protocol: UDP
      port: 13133
    - protocol: UDP
      port: 4317