name: Java CI

on: [push]

jobs:
  atriac-test-results:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Maven
        working-directory: ./atriac-test-results
        run: mvn clean verify
      - name: Build with Maven
        working-directory: ./atriac-test-results
        run: mvn --batch-mode --update-snapshots package -DskipTests

  test-result-visualizer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Maven
        working-directory: ./test-result-visualizer
        run: mvn clean verify
      - name: Build with Maven
        working-directory: ./test-result-visualizer
        run: mvn --batch-mode --update-snapshots package -DskipTests